# Generated by Django 5.0.2 on 2024-03-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branches",
            options={"verbose_name": "Филиал", "verbose_name_plural": "Филиалы"},
        ),
        migrations.AlterModelOptions(
            name="branchworkdays",
            options={"verbose_name_plural": "График филиала"},
        ),
        migrations.AlterField(
            model_name="branches",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Фото заведения"
            ),
        ),
        migrations.AlterField(
            model_name="branches",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Фото заведения"
            ),
        ),
        migrations.AlterField(
            model_name="branches",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Фото заведения"
            ),
        ),
        migrations.AlterField(
            model_name="branches",
            name="image4",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Фото заведения"
            ),
        ),
        migrations.AlterField(
            model_name="branches",
            name="link_on_2gis",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Ссылка на 2Gis"
            ),
        ),
        migrations.AlterField(
            model_name="branches",
            name="table_quantity",
            field=models.PositiveIntegerField(
                db_index=True, null=True, verbose_name="Количество столов"
            ),
        ),
        migrations.AddIndex(
            model_name="branches",
            index=models.Index(
                fields=["branch_name"], name="admins_bran_branch__eaf95c_idx"
            ),
        ),
    ]
