# Generated by Django 5.0.2 on 2024-03-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0002_alter_branches_options_alter_branchworkdays_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branches",
            name="schedule",
        ),
        migrations.AddField(
            model_name="branches",
            name="schedule",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="branch_schedule",
                to="admins.branchworkdays",
            ),
        ),
    ]
