# Generated by Django 5.0.2 on 2024-03-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0003_remove_branches_schedule_branches_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branches",
            name="schedule",
            field=models.ManyToManyField(
                blank=True, related_name="branch_schedule", to="admins.branchworkdays"
            ),
        ),
    ]
