# Generated by Django 5.0.2 on 2024-03-04 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0004_alter_branches_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Категория"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Фото категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterField(
            model_name="branches",
            name="branch_name",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="Название филиала"
            ),
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_dish",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Наименование"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=2, verbose_name="Стоимость"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_category",
                        to="admins.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Меню",
                "verbose_name_plural": "Меню",
            },
        ),
        migrations.AddField(
            model_name="branches",
            name="menu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branch_menu",
                to="admins.menu",
                verbose_name="Меню",
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=150, verbose_name="Наименование"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Количество")),
                ("limit", models.PositiveIntegerField(default=0, verbose_name="Лимит")),
                ("arrival_date", models.DateField(verbose_name="Дата прихода")),
                (
                    "unit_quantity",
                    models.CharField(
                        choices=[
                            ("kg", "кг."),
                            ("g", "гр."),
                            ("l", "лит."),
                            ("ml", "мл."),
                            ("unit", "шт"),
                        ],
                        max_length=20,
                        verbose_name="Единица измерения (Количество)",
                    ),
                ),
                (
                    "product_category",
                    models.CharField(
                        choices=[
                            ("ready_products", "Готовые продукты"),
                            ("raw_materials", "Сырье"),
                        ],
                        max_length=20,
                        verbose_name="Категория продукта",
                    ),
                ),
                (
                    "is_running_out",
                    models.BooleanField(
                        default=False, verbose_name="Заканчивающийся продукт"
                    ),
                ),
                (
                    "branch",
                    models.ManyToManyField(
                        related_name="branch_in_product",
                        to="admins.branches",
                        verbose_name="Филилалы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["-arrival_date", "product_name"],
            },
        ),
        migrations.AddField(
            model_name="menu",
            name="product_raw",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admins.product",
                verbose_name="Состав блюда и граммовка",
            ),
        ),
        migrations.CreateModel(
            name="ExtraProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extra_product_quantity",
                    models.CharField(
                        choices=[
                            ("kg", "кг."),
                            ("g", "гр."),
                            ("l", "лит."),
                            ("ml", "мл."),
                            ("unit", "шт"),
                        ],
                        max_length=20,
                        verbose_name="Количество",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_product",
                        to="admins.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доп. продукт",
                "verbose_name_plural": "Доп. продукты",
            },
        ),
    ]
