# Generated by Django 5.0.2 on 2024-03-04 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0005_category_alter_branches_branch_name_menu_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="product_raw",
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "choice_unit",
                    models.CharField(
                        choices=[
                            ("kg", "кг."),
                            ("g", "гр."),
                            ("l", "лит."),
                            ("ml", "мл."),
                            ("unit", "шт"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="admins.menu"
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="admins.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тех. карта",
                "verbose_name_plural": "Тех. карта",
            },
        ),
        migrations.AddField(
            model_name="menu",
            name="product_raw",
            field=models.ManyToManyField(
                through="admins.Recipe",
                to="admins.product",
                verbose_name="Состав блюда и граммовка",
            ),
        ),
    ]
