# Generated by Django 5.0.2 on 2024-03-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0006_remove_menu_product_raw_recipe_menu_product_raw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Стоимость"
            ),
        ),
    ]
