# Generated by Django 5.0.2 on 2024-03-04 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0007_alter_menu_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="product_raw",
            new_name="products",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="products",
            new_name="product",
        ),
    ]
