# Generated by Django 5.0.2 on 2024-03-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0008_rename_product_raw_menu_products_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extraproduct",
            name="quantity",
            field=models.IntegerField(null=True, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="extraproduct",
            name="extra_product_quantity",
            field=models.CharField(
                choices=[
                    ("kg", "кг."),
                    ("g", "гр."),
                    ("l", "лит."),
                    ("ml", "мл."),
                    ("unit", "шт"),
                ],
                max_length=20,
                verbose_name="Измерения",
            ),
        ),
    ]
