# Generated by Django 5.0.2 on 2024-03-06 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0009_extraproduct_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branches",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branch_menu",
                to="admins.menu",
                verbose_name="Меню",
            ),
        ),
    ]
