# Generated by Django 5.0.2 on 2024-03-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0010_alter_branches_menu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branches",
            name="menu",
        ),
        migrations.AddField(
            model_name="branches",
            name="menu",
            field=models.ManyToManyField(
                blank=True,
                related_name="branch_menu",
                to="admins.menu",
                verbose_name="Меню",
            ),
        ),
    ]
