# Generated by Django 5.0.2 on 2024-02-18 19:07

import apps.user_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_app",
            "0002_remove_clientprofile_otp_remove_employeeprofile_otp_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientprofile",
            options={
                "verbose_name": "Профиль клиента",
                "verbose_name_plural": "Профили клиентов",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Все пользователи",
                "verbose_name_plural": "Мои пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="employeeprofile",
            options={
                "verbose_name": "Профиль сотрудника",
                "verbose_name_plural": "Профили сотрудников",
            },
        ),
        migrations.AlterModelOptions(
            name="employeeschedule",
            options={
                "verbose_name": "Загаловка графика (Ночь, День и т.д)",
                "verbose_name_plural": "Загаловка графиков (Ночь, День и т.д)",
            },
        ),
        migrations.AlterModelOptions(
            name="employeeworkdays",
            options={"verbose_name_plural": "График сотрудников"},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[apps.user_app.models.validate_date_of_birth],
                verbose_name="Дата рождения",
            ),
        ),
    ]
