# Generated by Django 5.0.2 on 2024-02-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0004_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="otp_expiration",
            field=models.DateTimeField(null=True),
        ),
    ]
