# Generated by Django 5.0.2 on 2024-02-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0006_customuser_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="otp",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Код"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="otp_expiration",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Срок кода"),
        ),
    ]
