# Generated by Django 5.0.2 on 2024-02-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0007_alter_customuser_otp_alter_customuser_otp_expiration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(blank=True, max_length=128, verbose_name="password"),
        ),
    ]
