# Generated by Django 5.0.2 on 2024-02-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0008_alter_customuser_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="otp",
            field=models.PositiveIntegerField(
                blank=True, max_length=4, null=True, verbose_name="Код"
            ),
        ),
    ]
