# Generated by Django 5.0.2 on 2024-03-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0009_alter_customuser_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="otp",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Код"
            ),
        ),
    ]
