# Generated by Django 5.0.2 on 2024-03-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0010_alter_customuser_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_super_admin",
            field=models.BooleanField(default=False),
        ),
    ]
